uiFolder: "some folder"
swagger:
    resourcePackage: il.tr.server.resource,
    schemes:
      - https
server:
  applicationConnectors:
  - type: http
    port: 9000
  - type: https
    port: 8443
    keyStorePath: src/main/resources/server.keystore
    keyStorePassword: "password"
    validateCerts: false
    validatePeers: false
  adminConnectors:
  - type: http
    port: 9001